/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTamuRouteImport } from './routes/dashboard.tamu'
import { Route as DashboardPengaturanRouteImport } from './routes/dashboard.pengaturan'
import { Route as DashboardMempelaiRouteImport } from './routes/dashboard.mempelai'
import { Route as DashboardGaleriRouteImport } from './routes/dashboard.galeri'
import { Route as DashboardAcaraRouteImport } from './routes/dashboard.acara'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTamuRoute = DashboardTamuRouteImport.update({
  id: '/tamu',
  path: '/tamu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPengaturanRoute = DashboardPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMempelaiRoute = DashboardMempelaiRouteImport.update({
  id: '/mempelai',
  path: '/mempelai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGaleriRoute = DashboardGaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAcaraRoute = DashboardAcaraRouteImport.update({
  id: '/acara',
  path: '/acara',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/acara': typeof DashboardAcaraRoute
  '/dashboard/galeri': typeof DashboardGaleriRoute
  '/dashboard/mempelai': typeof DashboardMempelaiRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRoute
  '/dashboard/tamu': typeof DashboardTamuRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/acara': typeof DashboardAcaraRoute
  '/dashboard/galeri': typeof DashboardGaleriRoute
  '/dashboard/mempelai': typeof DashboardMempelaiRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRoute
  '/dashboard/tamu': typeof DashboardTamuRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/acara': typeof DashboardAcaraRoute
  '/dashboard/galeri': typeof DashboardGaleriRoute
  '/dashboard/mempelai': typeof DashboardMempelaiRoute
  '/dashboard/pengaturan': typeof DashboardPengaturanRoute
  '/dashboard/tamu': typeof DashboardTamuRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/acara'
    | '/dashboard/galeri'
    | '/dashboard/mempelai'
    | '/dashboard/pengaturan'
    | '/dashboard/tamu'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/acara'
    | '/dashboard/galeri'
    | '/dashboard/mempelai'
    | '/dashboard/pengaturan'
    | '/dashboard/tamu'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/acara'
    | '/dashboard/galeri'
    | '/dashboard/mempelai'
    | '/dashboard/pengaturan'
    | '/dashboard/tamu'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tamu': {
      id: '/dashboard/tamu'
      path: '/tamu'
      fullPath: '/dashboard/tamu'
      preLoaderRoute: typeof DashboardTamuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pengaturan': {
      id: '/dashboard/pengaturan'
      path: '/pengaturan'
      fullPath: '/dashboard/pengaturan'
      preLoaderRoute: typeof DashboardPengaturanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mempelai': {
      id: '/dashboard/mempelai'
      path: '/mempelai'
      fullPath: '/dashboard/mempelai'
      preLoaderRoute: typeof DashboardMempelaiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/galeri': {
      id: '/dashboard/galeri'
      path: '/galeri'
      fullPath: '/dashboard/galeri'
      preLoaderRoute: typeof DashboardGaleriRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/acara': {
      id: '/dashboard/acara'
      path: '/acara'
      fullPath: '/dashboard/acara'
      preLoaderRoute: typeof DashboardAcaraRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAcaraRoute: typeof DashboardAcaraRoute
  DashboardGaleriRoute: typeof DashboardGaleriRoute
  DashboardMempelaiRoute: typeof DashboardMempelaiRoute
  DashboardPengaturanRoute: typeof DashboardPengaturanRoute
  DashboardTamuRoute: typeof DashboardTamuRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAcaraRoute: DashboardAcaraRoute,
  DashboardGaleriRoute: DashboardGaleriRoute,
  DashboardMempelaiRoute: DashboardMempelaiRoute,
  DashboardPengaturanRoute: DashboardPengaturanRoute,
  DashboardTamuRoute: DashboardTamuRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
