-- ============================================================
-- Fix Missing Templates
-- Jalankan di MySQL server: mysql -u user -p database < fix-missing-templates.sql
-- Atau paste di phpMyAdmin / cPanel MySQL
-- ============================================================

SET NAMES utf8mb4;

-- Template yang hilang: the-wedding-navy, the-wedding-sage, the-wedding-pink,
-- the-wedding-purple, tropical-paradise, vintage-rustic, white-elegance, template-4

INSERT INTO `templates` (`title`, `slug`, `file`, `file_type`, `preset`, `url`, `grade`, `price`, `publish`, `user_id`, `ip_addr`, `created_at`, `updated_at`)
VALUES

('The Wedding Navy', 'the-wedding-navy', NULL, 'image',
'{"design":{"title":{"color":"#1e3a5f","font":"Merriweather","size":28},"content":{"color":"#4a5568","font":"Didact Gothic","size":14},"button":{"color":"#ffffff","background":"#1e3a5f"},"background":"#f0f4f8","template":null},"cover":{"name":{"female":"Mempelai Wanita","male":"Mempelai Pria","size":"60","style":"default"},"content":"Kami mengundang kehadiran Bapak/Ibu/Saudara/i di hari istimewa kami.","button":"Buka Undangan","description":{"top":"Assalamualaikum Warahmatullahi Wabarakatuh","bottom":"Waalaikumussalaam Warahmatullahi Wabarakatuh","image":{"method":"none","image":""}}},"profile":{"name":{"female":"Nama Mempelai Wanita","male":"Nama Mempelai Pria"},"photo":{"female":{"method":"none","frame":"","image":""},"male":{"method":"none","frame":"","image":""}},"instagram":{"show":false,"female":"","male":""},"parent":{"show":false,"female":{"childhood":"1","father":"","mother":""},"male":{"childhood":"1","father":"","mother":""}}},"detail":{"calendar":{"save":{"content":"Simpan Tanggal","show":false},"date":"","time":"09:00","timezone":"wib"},"countdown":{"show":true,"style":"default"},"location":{"address":"","map":""},"additional":{"show":false,"closing":"Merupakan suatu kehormatan dan kebahagiaan bagi kami.","special":[]}},"additional":{"live":{"show":false,"app":"youtube","link":"","content":""},"protocol":{"show":false,"code":[],"title":"Protokol Kesehatan","content":""}},"quote":{"content":"Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri. Q.S Ar-Rum: 21","decoration":""},"music":{"title":"","url":"","show":false},"rsvp":{"title":"Konfirmasi Kehadiran","content":"Mohon konfirmasi kehadiran Anda.","date":"","yes":{"option":"Hadir","content":"Terima kasih!"},"no":{"option":"Tidak Hadir","content":"Terima kasih."}},"wishes":{"public":true,"title":"Ucapan & Doa","content":"Doa restu Anda sangat berarti bagi kami."},"gift":{"show":false,"title":"Amplop Digital","content":"","bank":{"option":"bca","code":"","name":""}}}',
'the-wedding-navy', 'basic', 0, 'publish', 1, '127.0.0.1', NOW(), NOW()),

('The Wedding Sage', 'the-wedding-sage', NULL, 'image',
'{"design":{"title":{"color":"#6b8f71","font":"Satisfy","size":32},"content":{"color":"#5a7a6a","font":"Didact Gothic","size":14},"button":{"color":"#ffffff","background":"#6b8f71"},"background":"#f7f3ee","template":null},"cover":{"name":{"female":"Mempelai Wanita","male":"Mempelai Pria","size":"60","style":"default"},"content":"Kami mengundang kehadiran Bapak/Ibu/Saudara/i di hari istimewa kami.","button":"Buka Undangan","description":{"top":"Assalamualaikum Warahmatullahi Wabarakatuh","bottom":"Waalaikumussalaam Warahmatullahi Wabarakatuh","image":{"method":"none","image":""}}},"profile":{"name":{"female":"Nama Mempelai Wanita","male":"Nama Mempelai Pria"},"photo":{"female":{"method":"none","frame":"","image":""},"male":{"method":"none","frame":"","image":""}},"instagram":{"show":false,"female":"","male":""},"parent":{"show":false,"female":{"childhood":"1","father":"","mother":""},"male":{"childhood":"1","father":"","mother":""}}},"detail":{"calendar":{"save":{"content":"Simpan Tanggal","show":false},"date":"","time":"09:00","timezone":"wib"},"countdown":{"show":true,"style":"default"},"location":{"address":"","map":""},"additional":{"show":false,"closing":"Merupakan suatu kehormatan dan kebahagiaan bagi kami.","special":[]}},"additional":{"live":{"show":false,"app":"youtube","link":"","content":""},"protocol":{"show":false,"code":[],"title":"Protokol Kesehatan","content":""}},"quote":{"content":"Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri. Q.S Ar-Rum: 21","decoration":""},"music":{"title":"","url":"","show":false},"rsvp":{"title":"Konfirmasi Kehadiran","content":"Mohon konfirmasi kehadiran Anda.","date":"","yes":{"option":"Hadir","content":"Terima kasih!"},"no":{"option":"Tidak Hadir","content":"Terima kasih."}},"wishes":{"public":true,"title":"Ucapan & Doa","content":"Doa restu Anda sangat berarti bagi kami."},"gift":{"show":false,"title":"Amplop Digital","content":"","bank":{"option":"bca","code":"","name":""}}}',
'the-wedding-sage', 'basic', 0, 'publish', 1, '127.0.0.1', NOW(), NOW()),

('The Wedding Pink', 'the-wedding-pink', NULL, 'image',
'{"design":{"title":{"color":"#d4a5a5","font":"Satisfy","size":32},"content":{"color":"#8a6a6a","font":"Didact Gothic","size":14},"button":{"color":"#ffffff","background":"#d4a5a5"},"background":"#fdf5f5","template":null},"cover":{"name":{"female":"Mempelai Wanita","male":"Mempelai Pria","size":"60","style":"default"},"content":"Kami mengundang kehadiran Bapak/Ibu/Saudara/i di hari istimewa kami.","button":"Buka Undangan","description":{"top":"Assalamualaikum Warahmatullahi Wabarakatuh","bottom":"Waalaikumussalaam Warahmatullahi Wabarakatuh","image":{"method":"none","image":""}}},"profile":{"name":{"female":"Nama Mempelai Wanita","male":"Nama Mempelai Pria"},"photo":{"female":{"method":"none","frame":"","image":""},"male":{"method":"none","frame":"","image":""}},"instagram":{"show":false,"female":"","male":""},"parent":{"show":false,"female":{"childhood":"1","father":"","mother":""},"male":{"childhood":"1","father":"","mother":""}}},"detail":{"calendar":{"save":{"content":"Simpan Tanggal","show":false},"date":"","time":"09:00","timezone":"wib"},"countdown":{"show":true,"style":"default"},"location":{"address":"","map":""},"additional":{"show":false,"closing":"Merupakan suatu kehormatan dan kebahagiaan bagi kami.","special":[]}},"additional":{"live":{"show":false,"app":"youtube","link":"","content":""},"protocol":{"show":false,"code":[],"title":"Protokol Kesehatan","content":""}},"quote":{"content":"Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri. Q.S Ar-Rum: 21","decoration":""},"music":{"title":"","url":"","show":false},"rsvp":{"title":"Konfirmasi Kehadiran","content":"Mohon konfirmasi kehadiran Anda.","date":"","yes":{"option":"Hadir","content":"Terima kasih!"},"no":{"option":"Tidak Hadir","content":"Terima kasih."}},"wishes":{"public":true,"title":"Ucapan & Doa","content":"Doa restu Anda sangat berarti bagi kami."},"gift":{"show":false,"title":"Amplop Digital","content":"","bank":{"option":"bca","code":"","name":""}}}',
'the-wedding-pink', 'basic', 0, 'publish', 1, '127.0.0.1', NOW(), NOW()),

('The Wedding Purple', 'the-wedding-purple', NULL, 'image',
'{"design":{"title":{"color":"#6b3fa0","font":"Satisfy","size":32},"content":{"color":"#7a6a8a","font":"Didact Gothic","size":14},"button":{"color":"#ffffff","background":"#6b3fa0"},"background":"#f5f0fa","template":null},"cover":{"name":{"female":"Mempelai Wanita","male":"Mempelai Pria","size":"60","style":"default"},"content":"Kami mengundang kehadiran Bapak/Ibu/Saudara/i di hari istimewa kami.","button":"Buka Undangan","description":{"top":"Assalamualaikum Warahmatullahi Wabarakatuh","bottom":"Waalaikumussalaam Warahmatullahi Wabarakatuh","image":{"method":"none","image":""}}},"profile":{"name":{"female":"Nama Mempelai Wanita","male":"Nama Mempelai Pria"},"photo":{"female":{"method":"none","frame":"","image":""},"male":{"method":"none","frame":"","image":""}},"instagram":{"show":false,"female":"","male":""},"parent":{"show":false,"female":{"childhood":"1","father":"","mother":""},"male":{"childhood":"1","father":"","mother":""}}},"detail":{"calendar":{"save":{"content":"Simpan Tanggal","show":false},"date":"","time":"09:00","timezone":"wib"},"countdown":{"show":true,"style":"default"},"location":{"address":"","map":""},"additional":{"show":false,"closing":"Merupakan suatu kehormatan dan kebahagiaan bagi kami.","special":[]}},"additional":{"live":{"show":false,"app":"youtube","link":"","content":""},"protocol":{"show":false,"code":[],"title":"Protokol Kesehatan","content":""}},"quote":{"content":"Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri. Q.S Ar-Rum: 21","decoration":""},"music":{"title":"","url":"","show":false},"rsvp":{"title":"Konfirmasi Kehadiran","content":"Mohon konfirmasi kehadiran Anda.","date":"","yes":{"option":"Hadir","content":"Terima kasih!"},"no":{"option":"Tidak Hadir","content":"Terima kasih."}},"wishes":{"public":true,"title":"Ucapan & Doa","content":"Doa restu Anda sangat berarti bagi kami."},"gift":{"show":false,"title":"Amplop Digital","content":"","bank":{"option":"bca","code":"","name":""}}}',
'the-wedding-purple', 'basic', 0, 'publish', 1, '127.0.0.1', NOW(), NOW()),

('Tropical Paradise', 'tropical-paradise', NULL, 'image',
'{"design":{"title":{"color":"#00a86b","font":"Pacifico","size":28},"content":{"color":"#1a6b50","font":"Open Sans","size":14},"button":{"color":"#ffffff","background":"#00a86b"},"background":"#eaf7f0","template":null},"cover":{"name":{"female":"Mempelai Wanita","male":"Mempelai Pria","size":"60","style":"default"},"content":"Kami mengundang kehadiran Bapak/Ibu/Saudara/i di hari istimewa kami.","button":"Buka Undangan","description":{"top":"Assalamualaikum Warahmatullahi Wabarakatuh","bottom":"Waalaikumussalaam Warahmatullahi Wabarakatuh","image":{"method":"none","image":""}}},"profile":{"name":{"female":"Nama Mempelai Wanita","male":"Nama Mempelai Pria"},"photo":{"female":{"method":"none","frame":"","image":""},"male":{"method":"none","frame":"","image":""}},"instagram":{"show":false,"female":"","male":""},"parent":{"show":false,"female":{"childhood":"1","father":"","mother":""},"male":{"childhood":"1","father":"","mother":""}}},"detail":{"calendar":{"save":{"content":"Simpan Tanggal","show":false},"date":"","time":"09:00","timezone":"wib"},"countdown":{"show":true,"style":"default"},"location":{"address":"","map":""},"additional":{"show":false,"closing":"Merupakan suatu kehormatan dan kebahagiaan bagi kami.","special":[]}},"additional":{"live":{"show":false,"app":"youtube","link":"","content":""},"protocol":{"show":false,"code":[],"title":"Protokol Kesehatan","content":""}},"quote":{"content":"Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri. Q.S Ar-Rum: 21","decoration":""},"music":{"title":"","url":"","show":false},"rsvp":{"title":"Konfirmasi Kehadiran","content":"Mohon konfirmasi kehadiran Anda.","date":"","yes":{"option":"Hadir","content":"Terima kasih!"},"no":{"option":"Tidak Hadir","content":"Terima kasih."}},"wishes":{"public":true,"title":"Ucapan & Doa","content":"Doa restu Anda sangat berarti bagi kami."},"gift":{"show":false,"title":"Amplop Digital","content":"","bank":{"option":"bca","code":"","name":""}}}',
'tropical-paradise', 'premium', 0, 'publish', 1, '127.0.0.1', NOW(), NOW()),

('Vintage Rustic', 'vintage-rustic', NULL, 'image',
'{"design":{"title":{"color":"#8b7355","font":"Crimson Text","size":28},"content":{"color":"#5d4e37","font":"Lora","size":14},"button":{"color":"#ffffff","background":"#8b7355"},"background":"#f5f1e8","template":null},"cover":{"name":{"female":"Mempelai Wanita","male":"Mempelai Pria","size":"60","style":"default"},"content":"Kami mengundang kehadiran Bapak/Ibu/Saudara/i di hari istimewa kami.","button":"Buka Undangan","description":{"top":"Assalamualaikum Warahmatullahi Wabarakatuh","bottom":"Waalaikumussalaam Warahmatullahi Wabarakatuh","image":{"method":"none","image":""}}},"profile":{"name":{"female":"Nama Mempelai Wanita","male":"Nama Mempelai Pria"},"photo":{"female":{"method":"none","frame":"","image":""},"male":{"method":"none","frame":"","image":""}},"instagram":{"show":false,"female":"","male":""},"parent":{"show":false,"female":{"childhood":"1","father":"","mother":""},"male":{"childhood":"1","father":"","mother":""}}},"detail":{"calendar":{"save":{"content":"Simpan Tanggal","show":false},"date":"","time":"09:00","timezone":"wib"},"countdown":{"show":true,"style":"default"},"location":{"address":"","map":""},"additional":{"show":false,"closing":"Merupakan suatu kehormatan dan kebahagiaan bagi kami.","special":[]}},"additional":{"live":{"show":false,"app":"youtube","link":"","content":""},"protocol":{"show":false,"code":[],"title":"Protokol Kesehatan","content":""}},"quote":{"content":"Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri. Q.S Ar-Rum: 21","decoration":""},"music":{"title":"","url":"","show":false},"rsvp":{"title":"Konfirmasi Kehadiran","content":"Mohon konfirmasi kehadiran Anda.","date":"","yes":{"option":"Hadir","content":"Terima kasih!"},"no":{"option":"Tidak Hadir","content":"Terima kasih."}},"wishes":{"public":true,"title":"Ucapan & Doa","content":"Doa restu Anda sangat berarti bagi kami."},"gift":{"show":false,"title":"Amplop Digital","content":"","bank":{"option":"bca","code":"","name":""}}}',
'vintage-rustic', 'exclusive', 0, 'publish', 1, '127.0.0.1', NOW(), NOW()),

('White Elegance', 'white-elegance', NULL, 'image',
'{"design":{"title":{"color":"#2c2c2c","font":"Playfair Display","size":28},"content":{"color":"#6b6b6b","font":"Lato","size":14},"button":{"color":"#ffffff","background":"#c9a84c"},"background":"#faf9f7","template":null},"cover":{"name":{"female":"Mempelai Wanita","male":"Mempelai Pria","size":"60","style":"default"},"content":"Kami mengundang kehadiran Bapak/Ibu/Saudara/i di hari istimewa kami.","button":"Buka Undangan","description":{"top":"Assalamualaikum Warahmatullahi Wabarakatuh","bottom":"Waalaikumussalaam Warahmatullahi Wabarakatuh","image":{"method":"none","image":""}}},"profile":{"name":{"female":"Nama Mempelai Wanita","male":"Nama Mempelai Pria"},"photo":{"female":{"method":"none","frame":"","image":""},"male":{"method":"none","frame":"","image":""}},"instagram":{"show":false,"female":"","male":""},"parent":{"show":false,"female":{"childhood":"1","father":"","mother":""},"male":{"childhood":"1","father":"","mother":""}}},"detail":{"calendar":{"save":{"content":"Simpan Tanggal","show":false},"date":"","time":"09:00","timezone":"wib"},"countdown":{"show":true,"style":"default"},"location":{"address":"","map":""},"additional":{"show":false,"closing":"Merupakan suatu kehormatan dan kebahagiaan bagi kami.","special":[]}},"additional":{"live":{"show":false,"app":"youtube","link":"","content":""},"protocol":{"show":false,"code":[],"title":"Protokol Kesehatan","content":""}},"quote":{"content":"Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri. Q.S Ar-Rum: 21","decoration":""},"music":{"title":"","url":"","show":false},"rsvp":{"title":"Konfirmasi Kehadiran","content":"Mohon konfirmasi kehadiran Anda.","date":"","yes":{"option":"Hadir","content":"Terima kasih!"},"no":{"option":"Tidak Hadir","content":"Terima kasih."}},"wishes":{"public":true,"title":"Ucapan & Doa","content":"Doa restu Anda sangat berarti bagi kami."},"gift":{"show":false,"title":"Amplop Digital","content":"","bank":{"option":"bca","code":"","name":""}}}',
'white-elegance', 'exclusive', 0, 'publish', 1, '127.0.0.1', NOW(), NOW()),

('Forest Green', 'template-4', NULL, 'image',
'{"design":{"title":{"color":"#4a7c59","font":"Fraunces","size":28},"content":{"color":"#6b7c6d","font":"Inter","size":14},"button":{"color":"#ffffff","background":"#4a7c59"},"background":"#f5f0e8","template":null},"cover":{"name":{"female":"Mempelai Wanita","male":"Mempelai Pria","size":"60","style":"default"},"content":"Kami mengundang kehadiran Bapak/Ibu/Saudara/i di hari istimewa kami.","button":"Buka Undangan","description":{"top":"Assalamualaikum Warahmatullahi Wabarakatuh","bottom":"Waalaikumussalaam Warahmatullahi Wabarakatuh","image":{"method":"none","image":""}}},"profile":{"name":{"female":"Nama Mempelai Wanita","male":"Nama Mempelai Pria"},"photo":{"female":{"method":"none","frame":"","image":""},"male":{"method":"none","frame":"","image":""}},"instagram":{"show":false,"female":"","male":""},"parent":{"show":false,"female":{"childhood":"1","father":"","mother":""},"male":{"childhood":"1","father":"","mother":""}}},"detail":{"calendar":{"save":{"content":"Simpan Tanggal","show":false},"date":"","time":"09:00","timezone":"wib"},"countdown":{"show":true,"style":"default"},"location":{"address":"","map":""},"additional":{"show":false,"closing":"Merupakan suatu kehormatan dan kebahagiaan bagi kami.","special":[]}},"additional":{"live":{"show":false,"app":"youtube","link":"","content":""},"protocol":{"show":false,"code":[],"title":"Protokol Kesehatan","content":""}},"quote":{"content":"Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu istri-istri dari jenismu sendiri. Q.S Ar-Rum: 21","decoration":""},"music":{"title":"","url":"","show":false},"rsvp":{"title":"Konfirmasi Kehadiran","content":"Mohon konfirmasi kehadiran Anda.","date":"","yes":{"option":"Hadir","content":"Terima kasih!"},"no":{"option":"Tidak Hadir","content":"Terima kasih."}},"wishes":{"public":true,"title":"Ucapan & Doa","content":"Doa restu Anda sangat berarti bagi kami."},"gift":{"show":false,"title":"Amplop Digital","content":"","bank":{"option":"bca","code":"","name":""}}}',
'template-4', 'exclusive', 0, 'publish', 1, '127.0.0.1', NOW(), NOW())

ON DUPLICATE KEY UPDATE
    `title`     = VALUES(`title`),
    `url`       = VALUES(`url`),
    `grade`     = VALUES(`grade`),
    `price`     = VALUES(`price`),
    `publish`   = VALUES(`publish`),
    `preset`    = VALUES(`preset`),
    `updated_at`= NOW();

-- Verifikasi
SELECT id, title, slug, grade, publish FROM templates ORDER BY grade, title;
